### ISSUE TITLE
Pixhawk 5x vs 4

### ISSUE THREAD

**Issue by retoc71586** [VIS4ROB-lab/mav_hardware#1]
Good evening, I was just wondering what's the deal with the new Pixhawk 5x. Is it supposed to be a replacement for the PX4 or it is intended to have other purposes (it seems to be more powerful, and costly). 
What would you suggest to use for a first build?
PX4 has a lot of documentation so it feels like a safer choice also for integration with other onboard computers etc.
Thanks for the feedback :)

**Comment by ykompis** [comment]
Hi!
The Pixhawk v5x is the latest version of the Pixhawk autopilot standard and should be more powerful and robust than previous versions.
What's best for you highly depends on your application but most likely any version would work. If you are planning to interface the autopilot with an onboard computer you might not need the more advanced autopilot (since high-level path planning and collision avoidance can be offloaded to the onboard computer). In that case you might prefer a more mature autopilot with lots of documentation over the new version (although documentation is usually very good in the px4 ecosystem).
If you build your drone from a kit I would therefore suggest to use the standard provided with the kit (e.g. Holybro X500 v1 with a Pixhaw4 or Holybro X500 v2 with a Pixhawk 5x), otherwise choose the autopilot according to your application.
